# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rexample.proto\"\x17\n\x08send_msg\x12\x0b\n\x03uid\x18\x01 \x02(\x05\"\x16\n\x07\x61\x63k_msg\x12\x0b\n\x03msg\x18\x01 \x02(\t2-\n\x07\x45xample\x12\"\n\tSend_icmp\x12\t.send_msg\x1a\x08.ack_msg\"\x00')
)




_SEND_MSG = _descriptor.Descriptor(
  name='send_msg',
  full_name='send_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='send_msg.uid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=40,
)


_ACK_MSG = _descriptor.Descriptor(
  name='ack_msg',
  full_name='ack_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='ack_msg.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=64,
)

DESCRIPTOR.message_types_by_name['send_msg'] = _SEND_MSG
DESCRIPTOR.message_types_by_name['ack_msg'] = _ACK_MSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

send_msg = _reflection.GeneratedProtocolMessageType('send_msg', (_message.Message,), dict(
  DESCRIPTOR = _SEND_MSG,
  __module__ = 'example_pb2'
  # @@protoc_insertion_point(class_scope:send_msg)
  ))
_sym_db.RegisterMessage(send_msg)

ack_msg = _reflection.GeneratedProtocolMessageType('ack_msg', (_message.Message,), dict(
  DESCRIPTOR = _ACK_MSG,
  __module__ = 'example_pb2'
  # @@protoc_insertion_point(class_scope:ack_msg)
  ))
_sym_db.RegisterMessage(ack_msg)



_EXAMPLE = _descriptor.ServiceDescriptor(
  name='Example',
  full_name='Example',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=66,
  serialized_end=111,
  methods=[
  _descriptor.MethodDescriptor(
    name='Send_icmp',
    full_name='Example.Send_icmp',
    index=0,
    containing_service=None,
    input_type=_SEND_MSG,
    output_type=_ACK_MSG,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXAMPLE)

DESCRIPTOR.services_by_name['Example'] = _EXAMPLE

# @@protoc_insertion_point(module_scope)
