# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import example_pb2 as example__pb2


class ExampleStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Send_icmp = channel.unary_unary(
        '/Example/Send_icmp',
        request_serializer=example__pb2.send_msg.SerializeToString,
        response_deserializer=example__pb2.ack_msg.FromString,
        )


class ExampleServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Send_icmp(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExampleServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Send_icmp': grpc.unary_unary_rpc_method_handler(
          servicer.Send_icmp,
          request_deserializer=example__pb2.send_msg.FromString,
          response_serializer=example__pb2.ack_msg.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Example', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
